<a href="https://colab.research.google.com/github/umeshrawat/AI_Math_Vedas/blob/master/bert_embeddings_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Embedding(nn.Module):
   def __init__(self, vocab_size, max_len, d_model, n_segments = 2):
       super(Embedding, self).__init__()
       self.tok_embed = nn.Embedding(vocab_size, d_model)  # token embedding: E_dog, E_my
       self.pos_embed = nn.Embedding(max_len, d_model)  # position embedding: E_0, E_1 ...E_T
       self.seg_embed = nn.Embedding(n_segments, d_model)  # segment(token type) embedding
       self.norm = nn.LayerNorm(d_model)

   def forward(self, x, seg):
       seq_len = x.size(1) # 3
       pos = torch.arange(seq_len, dtype=torch.long) # [0, 1, 2]
       pos = pos.unsqueeze(0).expand_as(x)  # (seq_len,) -> (batch_size, seq_len)
       # [
       #   [0, 1, 2],
       #   [0, 1, 2]
       # ]
       embedding = self.tok_embed(x) + self.pos_embed(pos) + self.seg_embed(seg)
       return self.norm(embedding)

In [ ]:
x = torch.Tensor([[1, 2, 3], [10, 20, 30]])

In [ ]:
print(x)

tensor([[ 1.,  2.,  3.],
        [10., 20., 30.]])


In [ ]:
seq_len = x.size(1)
print("seq_len", seq_len) # 3
pos = torch.arange(seq_len, dtype=torch.long)
print("pos", pos)
print("pos.unsqueeze(0)", pos.unsqueeze(0))
print("pos.unsqueeze(0).expand_as(x)\n", pos.unsqueeze(0).expand_as(x))

seq_len 3
pos tensor([0, 1, 2])
pos.unsqueeze(0) tensor([[0, 1, 2]])
pos.unsqueeze(0).expand_as(x)
 tensor([[0, 1, 2],
        [0, 1, 2]])


In [ ]:
pos = torch.arange(3, dtype=torch.long)
print(pos)


tensor([0, 1, 2])
