<a href="https://colab.research.google.com/github/umeshrawat/AI_Math_Vedas/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating Tensors in PyTorch

In [ ]:
# !pip install torch
import torch

In [ ]:
tensor1= torch.rand(8,1,6,1)
print(tensor1.shape)
# tensor2= torch.rand(7,1,1,2)
tensor2= torch.rand(8,1,1,2)
print(tensor2.shape)

print( (tensor1 + tensor2).shape )

torch.Size([8, 1, 6, 1])
torch.Size([8, 1, 1, 2])
torch.Size([8, 1, 6, 2])


In [ ]:
import torch
# Create a 3-dimensional tensor with random values from a uniform distribution
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)

tensor([[[0.6061, 0.9099, 0.6885, 0.2565],
         [0.8600, 0.6573, 0.7965, 0.2407],
         [0.0334, 0.4150, 0.8617, 0.9719]],

        [[0.6070, 0.1488, 0.4834, 0.2877],
         [0.4945, 0.1699, 0.6405, 0.6896],
         [0.4553, 0.6425, 0.8732, 0.3345]]])


## Identity Tensor

In [ ]:
def identity_matrix_with_diag (n):
	tensor_ones = torch.ones (n, n) #
	# print(tensor_ones)
	# In the return statement, torch.diag converts the identity_tensor to one dimension
	# Using torch.diag again creates a 20 tensor from the 1D tensor
	return torch.diag(torch.diag(tensor_ones))

In [ ]:
def identity_matrix_with_sum(n) :
	zeros_tensor = torch.zeros (n, n)
	identity_tensor = torch.diag(torch.ones (n)) # torch.diag changes 1D 	to 2D tensor
	identity_matrix = zeros_tensor + identity_tensor # Element wise addition of 	two tensors
	return identity_matrix

In [ ]:
print(identity_matrix_with_diag(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
torch.diag(torch.diag(torch.ones(5,5)))
# torch.diag(torch.ones(2, 5, 5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch. tensor ([[1, 2], [3,4]])

tensor([[1, 2],
        [3, 4]])

## Basic Mathematical Operations on Tensors

In [ ]:
import torch
# Create a base tensor
base_tensor = torch. tensor ([[1, 2], [3,4]])
print("Base Tensor: \n", base_tensor)
print()
# Create another tensor
second_tensor = torch.tensor ([[2, 2], [1,1]])
print("Second Tensor: \n", second_tensor)
print()
# Addition
addition_tensor = base_tensor + second_tensor
print("Addition: \n", addition_tensor)
print()

# Subtraction
subtraction_tensor = base_tensor - second_tensor
print("Subtraction: \n", subtraction_tensor)
print()
# Multiplication
multiplication_tensor = base_tensor * second_tensor
print("Multiplication: \n", multiplication_tensor)
print()
# Division
division_tensor = base_tensor / second_tensor
print("Division: In", division_tensor)
print()


Base Tensor: 
 tensor([[1, 2],
        [3, 4]])

Second Tensor: 
 tensor([[2, 2],
        [1, 1]])

Addition: 
 tensor([[3, 4],
        [4, 5]])

Subtraction: 
 tensor([[-1,  0],
        [ 2,  3]])

Multiplication: 
 tensor([[2, 4],
        [3, 4]])

Division: In tensor([[0.5000, 1.0000],
        [3.0000, 4.0000]])



## Tensor indexing and slicing

In [ ]:
import torch
# Create a tensor with size (2, 3, 3)
tensor = torch.tensor ([
	[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
	[[10, 11, 12], [13, 14, 15],[16, 17,18]]
])
print ("Original Tensor:")
print (tensor)
print("\nTensor Shape:", tensor.shape)


Original Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

Tensor Shape: torch.Size([2, 3, 3])


## Tensor indexing and slicing

In [ ]:
# Row Slice (Slice of the second row)
row_slice = tensor[:, 1, :]
print("\nRow Slice:")
print (row_slice)
print ("Row Slice Shape:", row_slice.shape)




Row Slice:
tensor([[ 4,  5,  6],
        [13, 14, 15]])
Row Slice Shape: torch.Size([2, 3])


## Tensor indexing and slicing

In [ ]:
# Column Slice (Slice of the third column)
column_slice = tensor[:,:, 2]
print ("\nColumn Slice:")
print(column_slice)
print ("Column Slice Shape:", column_slice.shape)



Column Slice:
tensor([[ 3,  6,  9],
        [12, 15, 18]])
Column Slice Shape: torch.Size([2, 3])


## Tensor Indexing and Slicing

In [ ]:
# Mixed Slice (Mixed slice of rows and columns)
mixed_slice = tensor[:, 0:2, 1:3]
print("\nMixed Slice:")
print (mixed_slice)
print("Mixed Slice Shape:", mixed_slice.shape)




Mixed Slice:
tensor([[[ 2,  3],
         [ 5,  6]],

        [[11, 12],
         [14, 15]]])
Mixed Slice Shape: torch.Size([2, 2, 2])


## Tensor Broadcasting Examples

In [ ]:
tensor1 = torch.tensor([[1, 2, 3],[4, 5, 6]])
tensor2 = torch.tensor ([10,20,30])
print("Tensor 1: \n", tensor1)
print("Tensor 2: \n", tensor2)
print()
print('Tensor Shapes')
print(tensor1.shape)
print(tensor2.shape)
print()
print("Broadcast addition: ")
result = tensor1 + tensor2
print(result)

Tensor 1: 
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor 2: 
 tensor([10, 20, 30])

Tensor Shapes
torch.Size([2, 3])
torch.Size([3])

Broadcast addition: 
tensor([[11, 22, 33],
        [14, 25, 36]])


In [ ]:
# Create a tensor of shape (256, 256, 3)
tensor1= torch.rand(256, 256, 3)
print("Tensor 1:", tensor1[:1, :3, :])
# Create a tensor of shape (3, 2, 1)
tensor2 = torch.rand(3)
print("Tensor 2:", tensor2)
print()
# Perform broadcasting for multiplication
result = tensor1 * tensor2
print("Result:", result[:1, :3, :])

print()
print("Tensor 1 Shape:", tensor1.shape)
print("Tensor 2 Shape:", tensor2.shape)
print("Result Shape:", result.shape)

Tensor 1: tensor([[[0.3631, 0.1166, 0.5888],
         [0.6707, 0.1351, 0.4265],
         [0.1690, 0.0911, 0.1979]]])
Tensor 2: tensor([0.7465, 0.5574, 0.7761])

Result: tensor([[[0.2711, 0.0650, 0.4569],
         [0.5007, 0.0753, 0.3310],
         [0.1262, 0.0508, 0.1536]]])

Tensor 1 Shape: torch.Size([256, 256, 3])
Tensor 2 Shape: torch.Size([3])
Result Shape: torch.Size([256, 256, 3])


In [ ]:
tensor1 = torch.tensor ([[1, 2,3], [4,5,6]]) # shape: (2,3)
print("Tensor 1:", tensor1)
print()
tensor2 = torch.tensor([[10], [20]]) # shape: (2,1)
print("Tensor 2:", tensor2)
print()
# Perform broadcasting for multiplication
result = tensor1 * tensor2
print('Result', result)
print ("Broadcast Multiplication: \n", result.shape)

Tensor 1: tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor 2: tensor([[10],
        [20]])

Result tensor([[ 10,  20,  30],
        [ 80, 100, 120]])
Broadcast Multiplication: 
 torch.Size([2, 3])


In [ ]:
tensor1= torch.rand(8,1,6,1)
print("Tensor 1:", tensor1[:1, :, :, :])
print()

tensor2 = torch.rand(7,1,5)
print("Tensor 2", tensor2)
print()
# Perform broadcasting for multiplication
result = tensor1 * tensor2
print("Result:", result[:1, :, :, :])

print()
print("Tensor 1 Shape:", tensor1.shape)
print("Tensor 2 Shape:", tensor2.shape)
print("Result Shape:", result.shape)

Tensor 1: tensor([[[[0.5984],
          [0.0590],
          [0.5818],
          [0.3552],
          [0.9788],
          [0.4303]]]])

Tensor 2 tensor([[[0.9527, 0.1152, 0.8158, 0.1927, 0.8001]],

        [[0.3323, 0.1028, 0.5554, 0.7715, 0.9050]],

        [[0.9650, 0.7260, 0.7791, 0.3517, 0.6753]],

        [[0.4714, 0.5746, 0.7640, 0.6665, 0.5654]],

        [[0.9646, 0.7272, 0.5364, 0.6630, 0.0462]],

        [[0.9833, 0.4757, 0.7993, 0.0536, 0.1791]],

        [[0.5048, 0.5153, 0.4079, 0.4429, 0.3232]]])

Result: tensor([[[[0.5701, 0.0689, 0.4882, 0.1153, 0.4788],
          [0.0562, 0.0068, 0.0481, 0.0114, 0.0472],
          [0.5543, 0.0670, 0.4746, 0.1121, 0.4655],
          [0.3384, 0.0409, 0.2898, 0.0684, 0.2842],
          [0.9325, 0.1128, 0.7985, 0.1886, 0.7832],
          [0.4099, 0.0496, 0.3510, 0.0829, 0.3443]],

         [[0.1988, 0.0615, 0.3323, 0.4617, 0.5416],
          [0.0196, 0.0061, 0.0328, 0.0455, 0.0534],
          [0.1933, 0.0598, 0.3231, 0.4489, 0.5265],
       

In [ ]:
import numpy as np
np.random.randn(4,3)#.argmin(axis=1)#.sum(axis=0)
arr = [1, 2, 4], [9, 7, 6], [7, 14, 9], [10, 16, 12]
np.array(arr).argmax(axis=1)

array([2, 0, 1, 1])

## Tensor Reduction Examples

In [ ]:
# Create a tensor
tensor = torch.tensor([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]],dtype=torch.float64)
print()
print("Original Tensor:")
print(tensor)
print()
print("Tensor Shape:", tensor.shape)
print()

# tensor reduction operations
# Tensor Reduction Operations
print('Along Dim 0')
sum_result = torch.sum(tensor, dim=0)
mean_result = torch.mean(tensor, dim=0)
max_result = torch.max(tensor, dim=0)
min_result = torch.min(tensor, dim=0)
argmax_result = torch.argmax(tensor, dim=0)
argmin_result = torch.argmin(tensor, dim=0)

print(sum_result)
print(mean_result)
print(max_result)
print(min_result)
print(argmax_result)
print(argmin_result)

print('\n')

print('Along Dim 1')
sum_result = torch.sum(tensor, dim=1)
mean_result = torch.mean(tensor, dim=1)
max_result = torch.max(tensor, dim=1)
min_result = torch.min(tensor, dim=1)
argmax_result = torch.argmax(tensor, dim=1)
argmin_result = torch.argmin(tensor, dim=1)

print(sum_result)
print(mean_result)
print(max_result)
print(min_result)
print(argmax_result)
print(argmin_result)

print('\n')

# Tensor Reduction Operations
print("No dimension given")
sum_result = torch.sum(tensor)
mean_result = torch.mean(tensor)
max_result = torch.max(tensor)
min_result = torch.min(tensor)
argmax_result = torch.argmax(tensor)
argmin_result = torch.argmin(tensor)

print(sum_result)
print(mean_result)
print(max_result)
print(min_result)
print(argmax_result)
print(argmin_result)



Original Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

Tensor Shape: torch.Size([3, 3])

Along Dim 0
tensor([12., 15., 18.], dtype=torch.float64)
tensor([4., 5., 6.], dtype=torch.float64)
torch.return_types.max(
values=tensor([7., 8., 9.], dtype=torch.float64),
indices=tensor([2, 2, 2]))
torch.return_types.min(
values=tensor([1., 2., 3.], dtype=torch.float64),
indices=tensor([0, 0, 0]))
tensor([2, 2, 2])
tensor([0, 0, 0])


Along Dim 1
tensor([ 6., 15., 24.], dtype=torch.float64)
tensor([2., 5., 8.], dtype=torch.float64)
torch.return_types.max(
values=tensor([3., 6., 9.], dtype=torch.float64),
indices=tensor([2, 2, 2]))
torch.return_types.min(
values=tensor([1., 4., 7.], dtype=torch.float64),
indices=tensor([0, 0, 0]))
tensor([2, 2, 2])
tensor([0, 0, 0])


No dimension given
tensor(45., dtype=torch.float64)
tensor(5., dtype=torch.float64)
tensor(9., dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(8)
tensor(0)


## Contguous Example

In [ ]:
# Create a tensor of shape [4, 3]
x = torch.arange(12).view(4, 3)
print('Tensor:', x)
print('Stride:', x.stride())
print(x.is_contiguous())

Tensor: tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
Stride: (3, 1)
True


In [ ]:
y = x.t()
print('Tensor:', y)
print('Stride:', y.stride())
print(y.is_contiguous())

Tensor: tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])
Stride: (1, 3)
False


## Examples of view and reshape

In [ ]:
# Create a contiguous 2D tensor
tensor = torch. tensor([
	[1, 2, 3],
	[4, 5, 6]
])
# Reshape the tensor using view
reshaped_tensor = tensor.view(3, 2)
print("Original Tensor:")
print (tensor)
print ("\nReshaped Tensor:")
print (reshaped_tensor)



Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Examples of view and reshape

In [ ]:
import torch
# Create a non-contiguous 2D tensor using slicing
tensor = torch. tensor([[1, 2, 3, 4, 5, 6]])
sliced_tensor = tensor[:, :3]
# Reshape the tensor using reshape
# reshaped_tensor = torch.reshape(sliced_tensor, (1, 3))
# reshaped_tensor = torch.reshape(sliced_tensor, (3, 1))
print ("Original Tensor:")
print (sliced_tensor)
print("\nReshaped Tensor:")
print (reshaped_tensor)


Original Tensor:
tensor([[1, 2, 3]])

Reshaped Tensor:
tensor([[1],
        [2],
        [3]])


Slide 37 : The -1 trick in view()

In [ ]:
import torch
# Create a tensor with size (2, 4)
tensor = torch. tensor([
	[1, 2, 3, 4],
	[5, 6, 7, 8]
])
# Reshape the tensor using view and -1 trick
reshaped_tensor = tensor.view(-1, 2)
print("Original Tensor:")
print (tensor)
print ("\\nReshaped Tensor:")
print (reshaped_tensor)


Original Tensor:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
\nReshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
a= torch.ones(2,3,4)
b= a.view(1,4,-1)
print(b.shape)

torch.Size([1, 4, 6])


In [ ]:
## example
x = torch.arange(24).view(2, 3, 4)
print(x)
print()
print(x.view(1, 4, -1))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])


In [ ]:
x = torch.arange(20).view(1, 10,1, 2)
print(x)
print(x.shape)
print(x.squeeze(0))
print(x.squeeze().shape)# change dimension each side

tensor([[[[ 0,  1]],

         [[ 2,  3]],

         [[ 4,  5]],

         [[ 6,  7]],

         [[ 8,  9]],

         [[10, 11]],

         [[12, 13]],

         [[14, 15]],

         [[16, 17]],

         [[18, 19]]]])
torch.Size([1, 10, 1, 2])
tensor([[[ 0,  1]],

        [[ 2,  3]],

        [[ 4,  5]],

        [[ 6,  7]],

        [[ 8,  9]],

        [[10, 11]],

        [[12, 13]],

        [[14, 15]],

        [[16, 17]],

        [[18, 19]]])
torch.Size([10, 2])


In [ ]:
b

## Transpose

In [ ]:
# import torch
# Example tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print ("Original tensor:")
print (x)
print("Shape of original tensor:", x.shape)
# Transpose the tensor
y = torch.transpose (x, 0, 1)
print ("Transposed tensor:")
print (y)
print("Shape of transposed tensor:", y.shape)



Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of original tensor: torch.Size([2, 3])
Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape of transposed tensor: torch.Size([3, 2])


In [ ]:
# multi tensor setting
x = torch.arange(24).view(2, 3, 4)
print(x)
print(x.shape)
print()
y = torch.transpose(x, 1, 2)# what happens if I put 0 and 1?
y
# print(x.t())

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])



tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

## Concatenating tensors

In [ ]:
import torch
# Create tensors
tensor1 = torch.tensor ([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])
tensor2 = torch.tensor([
[10, 11, 12],
[13, 14, 15],
[16, 17, 18]
])
# Concatenate tensors along dimension 1
concatenated_tensor = torch.cat((tensor1, tensor2), dim=1)#what happens with dim 0?
# Display results
print ("Tensor 1:")
print (tensor1)
print ("\nTensor 2:")
print (tensor2)
print ("\nConcatenated Tensor:")
print (concatenated_tensor)



Tensor 1:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Tensor 2:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

Concatenated Tensor:
tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])


## Splitting Tensors

In [ ]:
import torch
# Create a tensor
tensor = torch.tensor([[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]
])
# Split the tensor along dimension 0 into two parts
split_tensors = torch.split(tensor, split_size_or_sections=2, dim=0)
# Display results
print("Original Tensor:")
print (tensor)
print ("\nSplit Tensors:")
for j, split_tensor in enumerate(split_tensors):
  print(f"Tensor split {j+1}", split_tensor)



Original Tensor:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Split Tensors:
Tensor split 1 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor split 2 tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
# how is this different from view?
# well with view, we are still keeping one tensor
tensor.view(2, 2, 3)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

## Stacking tensors

In [ ]:
import torch
# Create tensors
tensor1 = torch. tensor ([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])
tensor2 = torch.tensor([
[10, 11, 12],
[13, 14, 15],
[16, 17, 18]
])
# Stack tensors along a new dimension
stacked_tensor = torch.stack((tensor1, tensor2), dim=-1)
# tensors are 3x3
# dim = 0 will add a dimension to the combined 0th dimension
# combined -> 1x3x3 -> stacked 2x3x3
# dim=1 will add a dimension to the 1st dimension
# combined -> 3x1x3 -> 3x2x3
# dim=2 will add a dimension to the 2nd dimension
# combined -> 3x3x1 -> 3x3x2

# Display results
print ("Tensor 1:")
print (tensor1)
print("\nTensor 2:")
print (tensor2)
print ("\nStacked Tensor:")
print (stacked_tensor)



Tensor 1:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Tensor 2:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

Stacked Tensor:
tensor([[[ 1, 10],
         [ 2, 11],
         [ 3, 12]],

        [[ 4, 13],
         [ 5, 14],
         [ 6, 15]],

        [[ 7, 16],
         [ 8, 17],
         [ 9, 18]]])


In [ ]:
stacked_tensor.shape

torch.Size([3, 3, 2])

## Example of Gradient calculation - using Autograd

In [ ]:
import torch
# Enable gradient tracking
x = torch.tensor(3.0, requires_grad=True)
# Perform operations on the tensor
y = 2 * x + 1
z = y ** 2
# Compute gradients
z.backward()
# Access the computed gradients
x_grad = x.grad

print(x_grad)

tensor(28.)


Slide 52 : Detaching and no grad()

In [ ]:
import torch
# Create a tensor with tracking enabled
x = torch.tensor([3.0], requires_grad=True)
# Perform operations on the tensor
y = x**2 + 2*x + 1
# Stop tracking gradients using detach()
z = y.detach()

# Perform further operations without tracking
with torch.no_grad() :
  w = z * 2
print(w)

tensor([32.])


Slide 53 : Advanced Autograd operations

In [ ]:
import torch
x = torch. tensor([2.0], requires_grad=True)
y = torch.tensor([3.0], requires_grad=True)
z = x ** 2 + y ** 3
z.backward(retain_graph=True) # Specify retain_graph=True
print(x.grad) # Partial derivative of z with respect to x
print(y.grad) # Partial derivative of z with respect to y
z.backward (retain_graph=True)
print(x.grad) # Second-order partial derivative of z with respect to X
print(y.grad) # Second-order partial derivative of z with respect to y
z.backward ()
print(x.grad)
print(y.grad)

tensor([4.])
tensor([27.])
tensor([8.])
tensor([54.])
tensor([12.])
tensor([81.])


Slide 55: Advanced autograd operations

In [ ]:
import torch
from torch.autograd.functional import hessian

# Create a tensor with requires_grad=True
x = torch.tensor([[1.0, 2.0, 3.0], [2.5, 3.5, 4.5]], requires_grad=True)

print(x)
# Define a function that returns a scalar
def scalar_function(x):
  return (x ** 3).sum()

# Compute the Hessian matrix
hessian_matrix = hessian (scalar_function, x)

# Access the Hessian matrix
print (hessian_matrix)



tensor([[1.0000, 2.0000, 3.0000],
        [2.5000, 3.5000, 4.5000]], requires_grad=True)
tensor([[[[ 6.,  0.,  0.],
          [ 0.,  0.,  0.]],

         [[ 0., 12.,  0.],
          [ 0.,  0.,  0.]],

         [[ 0.,  0., 18.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [15.,  0.,  0.]],

         [[ 0.,  0.,  0.],
          [ 0., 21.,  0.]],

         [[ 0.,  0.,  0.],
          [ 0.,  0., 27.]]]])


 Slide 57: Example of Pytorch Eager mode

In [ ]:
import torch
# Initializing input tensors
a = torch.tensor(15.0,requires_grad=True)
b = torch.tensor(20.0,requires_grad=True)
# Enable eager mode execution
torch.set_grad_enabled(True)
# Computing the output
c = a * b
# Computing the gradients
c.backward()
# Collecting the output gradient of the
# output with respect to the input 'a'
derivative_out_a = a.grad
# Collecting the output gradient of the
# output with respect to the input 'b'
derivative_out_b = b.grad
# Displaying the outputs
print(f'a = {a}')
print(f'b = {b}')
print (f'c = {c}')
print(f'Derivative of c with respect to a = {derivative_out_a}')
print(f'Derivative of c with respect to b = {derivative_out_b}')



a = 15.0
b = 20.0
c = 300.0
Derivative of c with respect to a = 20.0
Derivative of c with respect to b = 15.0


Slide 60: Example of JIT

In [ ]:
import torch
import torch.nn as nn
# Define the model as a class
class MultiplyModel (nn.Module):
       def __init__(self):
          super(MultiplyModel, self).__init__()
          self.linear = nn.Linear(1, 1)
       def forward(self, x):
          return self.linear(x)

# Create an instance of the model
model = MultiplyModel()
# Create example inputs

a = torch.tensor([15.0])
b = torch.tensor([20.0])

# Compile the model to a static graph using JIT
model = torch.jit.trace(model, a)

# Execute the model on the inputs
c = model(a * b)

# Display the output
print (f'c = {c}')

# for p in model.parameters():
#     if p.requires_grad:
#          print(p.name, p.data)



c = tensor([85.8739], grad_fn=<ViewBackward0>)
